# This is a basic workflow to help you get started with Actions

name: MonPremierWorkflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Ma première action  
        run: echo Démarrage du job

      # Runs a set of commands using the runners shell
      - name: fin de mon premier job 
        run: |
          echo c\'est la fin du job ,
          echo workflow terminé.
  test:
    runs-on: ubuntu-latest
    steps: 
      #test1
      - name: mon premier test
        run: echo test
  deploy:
    runs-on: ubuntu-latest
    steps: 
      #déploiement
      - name: mon premier déploiement mais pas tout a fait parce que j'ai déployé à la zob le projet mENIfestation
        run: echo go go gadgeto déploiement
  
